---
nexus:
  type: leaf

  hostname: LEAF-1-N9K-3

  interfaces:
    physical:
      - id: 1/3
        switchport: disabled
        mtu: 9216
        medium: p2p
        unnumbered: lo0
        ospf:
          name: UNDERLAY
          area: 0.0.0.0
          network_type: point-to-point
        pim: sparse-mode
      - id: 1/4
        switchport: disabled
        mtu: 9216
        medium: p2p
        unnumbered: lo0
        ospf:
          name: UNDERLAY
          area: 0.0.0.0
          network_type: point-to-point
        pim: sparse-mode
      - id: 1/5
        switchport: enabled
        switchport_mode: access
        switchport_vlan: 10
    loopback:
      - id: lo0
        ip_address: 192.168.1.3
        ospf:
          name: UNDERLAY
          area: 0.0.0.0
          network_type: point-to-point
        pim: sparse-mode
      - id: lo1
        ip_address: 192.168.1.30
        ospf:
          name: UNDERLAY
          area: 0.0.0.0
          network_type: point-to-point
        pim: sparse-mode
    svis:
      - id: 10
        vrf: TEN1
        ip_address: 172.16.10.254
        mask: 24
        anycast_gateway: enabled
      - id: 99
        vrf: TEN1
        ip_forward: enabled

  ospf:
    - name: UNDERLAY

  bgp:
    asn: 65001
    router_id: 192.168.1.3
    timers:
      keep_alive: 7
      hold_on: 21
    address_families:
      - type: ipv4
        subtype: unicast
      - type: l2vpn
        subtype: evpn
        retain_rt: all
    neighbors:
      - ip_address: 192.168.1.1
        remote_asn: 65001
        update_source: lo0
        address_families:
          - type: ipv4
            subtype: unicast
            send_community: enabled
          - type: l2vpn
            subtype: evpn
            send_community: enabled
      - ip_address: 192.168.1.2
        remote_asn: 65001
        update_source: lo0
        address_families:
          - type: ipv4
            subtype: unicast
            send_community: enabled
          - type: l2vpn
            subtype: evpn
            send_community: enabled

  pim:
    rp_address: 192.168.1.1

  vrfs:
    - name: TEN1
      vni: 1099
      rd: auto
      address_families:
      - type: ipv4
        subtype: unicast
        route_target: auto

  vlans:
    - id: 10
      vni: 1010
    - id: 99
      vni: 1099

  vxlan:
      fabric_mac: A.B.C
      source: lo1
      host_reachability_protocol: bgp
      vnis:
        - id: 1010
          multicast: 230.10.10.100
          type: l2
          rd: auto
          route_target: auto
        - id: 1099
          type: l3
